name: Build and deploy JAR app to Azure Web App - thepierogi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
            java-version: 16



      - name: Build with Maven
        run: mvn clean install

      - name: Cache Maven archetypes
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml


  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'thepierogi'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_af0b43cf31c64844acb8e748c96899db }}
          package: '${{ github.workspace }}/target/*.jar'



