name: CI/CD


on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'

  workflow_dispatch:

jobs:


  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '16'
    - name: Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Run Maven tests
      run: mvn --batch-mode --update-snapshots verify
